### PR TITLE
Revert "Revert "Moved pomegranate to requirements.txt""

### PR DESCRIPTION
**Pull request by fridex**
Reverts fabric8-analytics/fabric8-analytics-stack-analysis#67

### CODE REVIEW

**Comment by fridex** [comment]
CC: @rootAvish

**Comment by rootAvish** [comment]
It seems to be a problem with dependency resolution, guess there was a reason it was written the way it was after all. Let me see if I can fix it otherwise we'll file a bug upstream in pip.

**Comment by fridex** [comment]
> It seems to be a problem with dependency resolution, guess there was a reason it was written the way it was after all. Let me see if I can fix it otherwise we'll file a bug upstream in pip.

Any progress on this? I'm about to close this PR.

**Comment by rootAvish** [comment]
Trying a docker build with this change to see if the issue still persists. We can close it if it fails. Takes about 20 minutes.

**Comment by rootAvish** [comment]
It fails. You can close it.

**Pull request closed without merging**
